### ISSUE TITLE
关于stylesheet的格式

### ISSUE THREAD

**Issue by hainuo** [soliury/react-native-html-render#10]
![image](https://cloud.githubusercontent.com/assets/421861/16538611/32dcfa08-405c-11e6-9820-068477b9bb19.png)
我想减少 中间空白的大小应该怎么设定样式

```
<HtmlRender value={'<div>'+str+'</div>'} stylesheet={
                    {
                    p:{
                    margin:0,
                    padding:0,
                    fontSize:14,
                    lineHeight:16}
                    }}/>
```

**Comment by osdio** [comment]
能把你的html贴给我看看么

**Comment by osdio** [comment]
因为我这个组件目前来说只是对markdown转过来的html有比较好的体验，但是其他的就不怎么滴了，之后我打算优化一下

**Comment by hainuo** [comment]
@soliury   源码https://github.com/pingang360/pgwapp/blob/master/src/containers/article.js#L122
我的代码 最后都被格式化为 <p>dddd</p> 之类的 
···

<p>不锈钢为什么也生锈?</p><p>当不锈钢管表面出现褐色锈斑(点)的时候,人们大感惊奇:认为“不锈钢是不生锈的,生锈就不是不锈钢了,可能是钢质出现了问题”。其实,这是对不锈钢缺乏了解的一种片面的错误看法。不锈钢在一定的条件下也会生锈的</p><p>不锈钢具有抵抗大气氧化的能力---即不锈性,同时也具有在含酸、碱、盐的介质中乃腐蚀的能力---即耐蚀性。但其抗腐蚀能力的大小是随其钢质本身化学组成、加互状态、使用条件及环境介质类型而改变的。如304钢管,在干燥清洁的大气中,有绝对优良的抗锈蚀能力,但将它移到海滨地区,在含有大量盐份的海雾中,很快就会生锈了;而316钢管则表现良好。因此,不是任何一种不锈钢,在任何环境下都能耐腐蚀,不生锈的。</p><p>表面膜受到破坏的形式很多,日常生活中多见的有如下几种:</p><p>不锈钢是靠其表面形成的一层极薄而坚固细密的稳定的富铬氧化膜(防护膜),防止氧原子的继续渗入、继续氧化,而获得抗锈蚀的能力。一旦有某种原因,这种薄膜遭到了不断地破坏,空气或液体中氧原子就会不断渗入或金属中铁原子不断地析离出来,形成疏松的氧化铁,金属表面也就受到不断地锈蚀。这种表面膜受到破坏的形式很多,日常生活中多见的有如下几种:</p><p></p><p>1.不锈钢表面存积着含有其他金属元素的粉尘或异类金属颗粒的附着物,在潮湿的空气中,附着物与不锈钢间的冷凝水,将二者连成一个微电池,引发了电化学反应,保护膜受到破坏,称之谓电化学腐蚀。</p><p></p><p>2.不锈钢表面粘附有机物汁液(如瓜菜、面汤、痰等),在有水氧情况下,构成有机酸,长时间则有机酸对金属表面的腐蚀。</p><p></p><p>3.不锈钢表面粘附含有酸、碱、盐类物质(如装修墙壁的碱水、石灰水喷溅),引起局部腐蚀。</p><p></p><p>4.在有污染的空气中(如含有大量硫化物、氧化碳、氧化氮的大气),遇冷凝水,形成硫酸、硝酸、醋酸液点,引起化学腐蚀。</p><p></p><p>为确保金属表面永久光亮,不被锈蚀,我们建议:</p><p>以上情况均可造成不锈钢表面防护膜的破坏引发锈蚀。所以,为确保金属表面永久光亮,不被锈蚀,我们建议:</p><p></p><p>1.必须经常对装饰不锈钢表面进行清洁擦洗,去除附着物,消除引发修饰的外界因素。</p><p></p><p>2.海边地区要使用316材质不锈钢,316材质能抵抗海水腐蚀。</p><p></p><p>3.市场上有些不锈钢管化学成分不能符合相应国家标准,达不到304材质要求。因此也会引起生锈,这就需要用户认真选择有信誉厂家的产品。</p><p></p><p>不锈钢为什么也会带磁?</p><p>人们常以为磁铁吸附不锈钢材,验证其优劣和真伪,不吸无磁,认为是好的,货真价实;吸者有磁性,则认为是冒牌假货。其实,这是一种极其片面的、不切实的错误的辨别方法。</p><p></p><p>不锈钢的种类繁多,常温下按组织结构可分为几类:</p><p>1.奥氏体型:如201、202、301、304、316等;</p><p></p><p>2.马氏体或铁素体型:如430、420、410等;</p><p>奥氏体型是无磁或弱磁性,马氏体或铁素体是有磁性的。</p><p></p><p>通常用作装饰管板的不锈钢多数是奥氏体型的304材质,一般来讲是无磁或弱磁的,但因冶炼造成化学成分波动或加工状态不同也可能出现磁性,但这不能认为是冒牌或不合格,这是什么原因呢?</p><p></p><p>上面提到奥氏体是无磁或弱磁性,而马氏体或铁素体是带磁性的,由于冶炼时成分偏析或热处理不当,会造成奥氏体304不锈钢中少量马氏体或铁素体组织。这样,304不锈钢中就会带有微弱的磁性。</p><p></p><p>另外,304不锈钢经过冷加工,组织结构也会向马氏体转化,冷加工变形度越大,马氏体转化越多,钢的磁性也越大。如同一批号的钢带,生产Φ76管,无明显磁感,生产Φ9.5管。因泠弯变形较大磁感就明显一些,生产方矩形管因变形量比圆管大,特别是折角部分,变形更激烈磁性更明显。</p><p></p><p>要想完全消除上述原因造成的304钢的磁性,可通过高温固溶处理开恢复稳定奥氏体组织,从而消去磁性。</p><p></p><p>特别要提出的是,因上面原因造成的304不锈钢的磁性,与其他材质的不锈钢,如430、碳钢的磁性完全不是同一级别的,也就是说304钢的磁性始终显示的是弱磁性。</p><p></p><p>这就告诉我们,如果不锈钢带弱磁性或完全不带磁性,应判别为304或316材质;如果与碳钢的磁性一样,显示出强磁性,因判别为不是304材质。</p><p></p><p>我们建议:</p><p>买不锈钢,就到“拼钢网现货商城”,我们能做的是,在坚持真材实厚的产品价值理念上,通过对自身体系的不断完善,给您最实惠的价格,您还在等什么,快快点击:pingang360.com~轻松一点,很容易就购了。</p><p></p>

···
我也自reactnative.cn上提问了 http://bbs.reactnative.cn/topic/1737/%E5%85%B3%E4%BA%8Eview%E7%9A%84style%E5%AE%9A%E4%B9%89 

昨天的时候  修改了pwrapper 没有警告 ，今天重新打开 ios模拟器发现有警告了。 还请给帮助

**Comment by hainuo** [comment]
今天经过研究已经搞明白了这个问题，我可以通过设置pwrapper的margin来控制两个<p>节点间的空间。 
也在reactnative.cn网站上详细截图说明了， 多谢你 @soliury
