### ISSUE TITLE
What license are you offering for this project?

### ISSUE THREAD

**Issue by zharley** [soliury/react-native-html-render#4]
Here's some info about licenses on GitHub if you need it.

https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository

Suggestion:

https://opensource.org/licenses/MIT

Really cool project, BTW.

**Comment by osdio** [comment]
Ok, it's MIT, I will add the licenses later

**Comment by osdio** [comment]
Have add the MIT license
