### ISSUE TITLE
Unable to resolve module Dimensions.

### ISSUE THREAD

**Issue by r0st1kuzh** [soliury/react-native-html-render#5]
Hello, I've installed react-native-html-render "1.0.2".
When I run project I am getting:
`Unable to resolve module Dimensions from /Users/r0st1k/SWAN/react-app/node_modules/react-native-html-render/lib/htmlRender.js: Invalid directory /Users/node_modules/Dimensions`

When I've installed dimensions module through npm I get the same message. 

I know this is not a right way to do, but when I've corrected 
`var Dimensions = require('Dimensions')` to `var Dimensions = require('dimensions')` in htmlRender.js it finds dimensions but gives me next error:
`Unable to resolve module fs from /Users/r0st1k/SWAN/react-app/node_modules/dimensions/index.js: Invalid directory /Users/node_modules/fs`

Please advise what to do to use your module.

Now using node v5.2.0 (npm v3.5.1)

**Comment by osdio** [comment]
Sorry to delay to reply. The older react-native version they use `dimensions` as `var Dimensions = require('Dimensions')`.

But now the current version , the use : `import React, { Dimensions } from 'react-native'`

**Comment by r0st1kuzh** [comment]
Thanks

**Comment by osdio** [comment]
I have fix it on a0a6bd0d248eb75c007356d92f6cb6a05cf32b54
